spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  aop:
    proxy-target-class: true


kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-uri: ${KAKAO_TOKEN_URI}
  userinfo-uri: ${KAKAO_USER_INFO}


jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_EXPIRATION}
    header: Authorization
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
    header: RefreshToken

feedback:
  hash:
    secret: ${FEEDBACK_HASH_SECRET}

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_IAM_ACCESS_KEY}
      secret-key: ${AWS_S3_IAM_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}