spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  data:
    redis:
      host: localhost
      port: 6379
      password:


kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-uri: ${KAKAO_TOKEN_URI}
  userinfo-uri: ${KAKAO_USER_INFO}


jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: 3600000 # 1 hour
    header: Authorization
  refresh:
    expiration: 86400000 # 1 day
    header: RefreshToken
  data:
    redis:
      host: localhost
      port: 6379
